import { Theme } from '../types';

export const elegantDark: Theme = {
  id: 'wechat-elegant-dark',
  name: '优雅暗色',
  platform: 'wechat',
  description: '深灰底 + 金色点缀，适合情感、夜读、高端品牌类内容。',
  tags: ['dark', 'elegant'],
  base: {
    maxWidth: '677px',
    background: '#1a1a1a',
    padding: '18px',
    fontFamily: "-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei',sans-serif",
    fontSize: '16px',
    lineHeight: '1.8',
    color: '#e6e6e6',
  },
  tokens: {
    primary: '#d4af37',
    secondary: '#bbbbbb',
    muted: '#9a9a9a',
    radius: '8px',
    space: '16px',
  },
  heading: {
    h1: {
      fontSize: '24px',
      fontWeight: 700,
      color: '#f5f5f5',
      marginTop: '28px',
      marginBottom: '14px',
      borderLeft: '5px solid #d4af37',
      paddingLeft: '12px',
      lineHeight: '1.4',
    },
    h2: {
      fontSize: '20px',
      fontWeight: 700,
      color: '#f5f5f5',
      marginTop: '24px',
      marginBottom: '12px',
      borderLeft: '4px solid #d4af37',
      paddingLeft: '10px',
    },
    h3: {
      fontSize: '17px',
      fontWeight: 600,
      color: '#f0f0f0',
      marginTop: '20px',
      marginBottom: '10px',
      borderLeft: '3px solid #d4af37',
      paddingLeft: '8px',
    },
  },
  paragraph: {
    base: { margin: '0 0 16px', lineHeight: '1.8', color: '#e6e6e6' },
    lead: { margin: '0 0 16px', fontSize: '17px', color: '#cfcfcf' },
  },
  divider: { type: 'gradient', color: '#d4af37', margin: '20px 0' },
  quote: {
    background: '#262626',
    borderLeft: '4px solid #d4af37',
    padding: '12px 16px',
    color: '#cfcfcf',
    fontStyle: 'normal',
  },
  card: {
    background: '#262626',
    border: '1px solid #3a3a3a',
    borderRadius: '8px',
    padding: '16px',
    boxShadow: 'none',
  },
  image: {
    borderRadius: '8px',
    border: 'none',
    maxWidth: '100%',
    captionColor: '#9a9a9a',
    captionFontSize: '13px',
    captionAlign: 'center',
  },
  list: { markerColor: '#d4af37', bullet: '•' },
  code: {
    background: '#262626',
    color: '#ffd479',
    fontFamily: "'SFMono-Regular',Consolas,monospace",
    padding: '2px 6px',
    borderRadius: '4px',
  },
};
