import { Theme } from '../types';

export const minimalLight: Theme = {
  id: 'wechat-minimal-light',
  name: '极简浅色',
  platform: 'wechat',
  description: '干净白底、微信绿点缀，适合绝大多数行业与日常推文。',
  tags: ['minimal', 'light', 'classic'],
  base: {
    maxWidth: '677px',
    background: '#ffffff',
    padding: '16px',
    fontFamily: "-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei','Segoe UI',sans-serif",
    fontSize: '16px',
    lineHeight: '1.75',
    color: '#1f2329',
  },
  tokens: {
    primary: '#07c160',
    secondary: '#10aeff',
    muted: '#8a8f99',
    radius: '8px',
    space: '16px',
  },
  heading: {
    h1: {
      fontSize: '24px',
      fontWeight: 700,
      color: '#1f2329',
      marginTop: '28px',
      marginBottom: '14px',
      borderLeft: '5px solid #07c160',
      paddingLeft: '12px',
      lineHeight: '1.4',
    },
    h2: {
      fontSize: '20px',
      fontWeight: 700,
      color: '#1f2329',
      marginTop: '24px',
      marginBottom: '12px',
      borderLeft: '4px solid #07c160',
      paddingLeft: '10px',
      lineHeight: '1.4',
    },
    h3: {
      fontSize: '17px',
      fontWeight: 600,
      color: '#1f2329',
      marginTop: '20px',
      marginBottom: '10px',
      borderLeft: '3px solid #07c160',
      paddingLeft: '8px',
    },
  },
  paragraph: {
    base: { margin: '0 0 16px', lineHeight: '1.75', color: '#1f2329' },
    lead: { margin: '0 0 16px', fontSize: '17px', color: '#4a4a4a', lineHeight: '1.8' },
  },
  divider: { type: 'line', color: '#e5e7eb', margin: '20px 0' },
  quote: {
    background: '#f6f8fa',
    borderLeft: '4px solid #07c160',
    padding: '12px 16px',
    color: '#57606a',
    fontStyle: 'normal',
  },
  card: {
    background: '#f6f8fa',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    padding: '16px',
    boxShadow: 'none',
  },
  image: {
    borderRadius: '8px',
    border: 'none',
    maxWidth: '100%',
    captionColor: '#8a8f99',
    captionFontSize: '13px',
    captionAlign: 'center',
  },
  list: { markerColor: '#07c160', bullet: '•' },
  code: {
    background: '#f6f8fa',
    color: '#d6336c',
    fontFamily: "'SFMono-Regular',Consolas,'Liberation Mono',monospace",
    padding: '2px 6px',
    borderRadius: '4px',
  },
};
