import { Theme } from '../types';

export const newsCard: Theme = {
  id: 'wechat-news-card',
  name: '卡片资讯',
  platform: 'wechat',
  description: '蓝调卡片式排版，适合资讯、干货、教程类长文。',
  tags: ['news', 'card', 'fresh'],
  base: {
    maxWidth: '677px',
    background: '#ffffff',
    padding: '16px',
    fontFamily: "-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei',sans-serif",
    fontSize: '16px',
    lineHeight: '1.75',
    color: '#2b2b2b',
  },
  tokens: {
    primary: '#2f6fed',
    secondary: '#10aeff',
    muted: '#909399',
    radius: '10px',
    space: '16px',
  },
  heading: {
    h1: {
      fontSize: '24px',
      fontWeight: 700,
      color: '#1a1a1a',
      marginTop: '28px',
      marginBottom: '14px',
      background: '#eef3ff',
      padding: '10px 14px',
      borderRadius: '8px',
    },
    h2: {
      fontSize: '20px',
      fontWeight: 700,
      color: '#1a1a1a',
      marginTop: '24px',
      marginBottom: '12px',
      borderLeft: '4px solid #2f6fed',
      paddingLeft: '10px',
    },
    h3: {
      fontSize: '17px',
      fontWeight: 600,
      color: '#1a1a1a',
      marginTop: '20px',
      marginBottom: '10px',
      borderBottom: '2px solid #eef3ff',
      paddingBottom: '6px',
    },
  },
  paragraph: {
    base: { margin: '0 0 16px', lineHeight: '1.75', color: '#2b2b2b' },
    lead: { margin: '0 0 16px', fontSize: '17px', color: '#4a4a4a' },
  },
  divider: { type: 'dots', color: '#2f6fed', margin: '20px 0' },
  quote: {
    background: '#eef3ff',
    borderLeft: '4px solid #2f6fed',
    padding: '12px 16px',
    color: '#3a4a6b',
    fontStyle: 'normal',
  },
  card: {
    background: '#f5f8ff',
    border: '1px solid #dbe6ff',
    borderRadius: '10px',
    padding: '16px',
    boxShadow: 'none',
  },
  image: {
    borderRadius: '10px',
    border: 'none',
    maxWidth: '100%',
    captionColor: '#909399',
    captionFontSize: '13px',
    captionAlign: 'center',
  },
  list: { markerColor: '#2f6fed', bullet: '▸' },
  code: {
    background: '#f5f8ff',
    color: '#c2185b',
    fontFamily: "'SFMono-Regular',Consolas,monospace",
    padding: '2px 6px',
    borderRadius: '4px',
  },
};
